import 'package:flutter/widgets.dart';
import 'lang_notifier.dart';

class AppLocalizations {
  final String locale;
  const AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) =>
      AppLocalizations(LangNotifier.of(context).value);

  String call(String key) =>
      _strings[locale]?[key] ?? _strings['ja']![key] ?? key;

  // ── 対応言語リスト ────────────────────────────────
  static const List<Map<String, String>> supportedLanguages = [
    {'code': 'ja', 'label': '日本語', 'flag': '🇯🇵'},
    {'code': 'en', 'label': 'English', 'flag': '🇺🇸'},
    {'code': 'zh', 'label': '中文', 'flag': '🇨🇳'},
    {'code': 'ko', 'label': '한국어', 'flag': '🇰🇷'},
    {'code': 'hi', 'label': 'हिन्दी', 'flag': '🇮🇳'},
    {'code': 'vi', 'label': 'Tiếng Việt', 'flag': '🇻🇳'},
    {'code': 'fil', 'label': 'Filipino', 'flag': '🇵🇭'},
  ];

  // ── 全翻訳文字列 ──────────────────────────────────
  static const Map<String, Map<String, String>> _strings = {
    // ════════════════════════════════════════════════
    'ja': {
      // タイトル画面
      'appName': '温度補正システム',
      'subtitle': '一体型仕上げ組',
      'statsBtn': '統計・データ',
      'langSelect': '言語を選択',
      // メインナビ
      'navCalcTitle': '温度補正計算',
      'navTableTitle': '主要寸法 補正早見表',
      'navHelpTitle': 'ヘルプ・使い方',
      // 計算画面
      'fieldSize': '製品の寸法 (mm)',
      'fieldMasterTemp': '模範温度 (°C)',
      'fieldWorkTemp': '製品温度 (°C)',
      'calcBtn': '計算実行',
      'resultCorrection': '今回の補正量',
      'resultConverted': '模範温度での換算寸法',
      'refTableTitle': '【参考】温度補正値一覧',
      'refTableTempDiff': '温度差',
      'refTableCorrection': '補正量 (mm)',
      'dialogConfirm': '確認',
      'dialogCancel': 'キャンセル',
      'dialogExec': '計算実行',
      'dialogTempWarn': '温度差が {diff}°C です。\n10°C以上ですが、入力値は正しいですか？',
      // 統計画面
      'statsTitle': '統計・データ',
      'tabGraph': 'グラフ',
      'tabData': 'データ一覧',
      'modeMonthly': '月別',
      'modeSize': '寸法別',
      'modeGroup': '50mmグループ',
      'howToUse': '使い方',
      'export': 'エクスポート',
      'deleteAllBtn': '全データ削除',
      'noData': 'データがありません',
      'colCategory': '区分',
      'colCount': '件数',
      'colAvg': '平均',
      'colMax': '最大',
      'colMin': '最小',
      'colStdDev': '標準偏差',
      'exportTitle': 'エクスポート形式',
      'exportDesc': 'ダウンロードフォルダに保存します。\n形式を選んでください。',
      'creatingCsv': 'CSVファイルを作成中...',
      'creatingExcel': 'Excelファイルを作成中...',
      'exportSuccess': '{n}ファイルをダウンロードフォルダに保存しました',
      'exportFail': 'エクスポート失敗：ストレージの権限を確認してください',
      'deleteAllTitle': '全データ削除',
      'deleteAllMsg': 'すべての記録データを削除します。\nこの操作は元に戻せません。\n\nよろしいですか？',
      'deleteTitle': '削除確認',
      'deleteMsg': 'このデータを削除しますか？',
      'deleteBtn': '削除',
      'selectCategory': '削除する区分を選択',
      'selectedCount': '{n}件選択中',
      'deleteCategoryBtn': '{n}区分を削除',
      'selectFirst': '区分を選択してください',
      // 統計ヘルプ
      'helpStatsTitle': '統計・データ　使い方',
      'helpGraphSection': 'グラフタブ',
      'helpGraphMode': '表示切替',
      'helpGraphModeDesc': '画面上部の「月別」「寸法別」「50mmグループ」ボタンで集計の切り方を切り替えられます。',
      'helpGraphColor': '棒グラフの色',
      'helpGraphColorDesc': '赤いバー → 製品温度が模範より高い（＋）\n青いバー → 製品温度が模範より低い（−）',
      'helpGraphTap': 'タップで詳細',
      'helpGraphTapDesc': 'グラフの棒をタップすると、区分名・平均温度差・件数がポップアップ表示されます。',
      'helpGraphTable': '集計テーブル',
      'helpGraphTableDesc': 'グラフ下部に各区分の件数・平均・最大・最小を一覧表示します。',
      'helpGraphAvg': '平均列の見方',
      'helpGraphAvgDesc': '平均列は黄色背景・太字で強調表示されます。\n赤字 → 製品温度が模範より高い\n青字 → 製品温度が模範より低い',
      'helpGraphSort': '並び替え',
      'helpGraphSortDesc': '集計テーブルの列ヘッダーをタップすると並び替えができます。▲▼アイコンで現在の並び順を確認できます。',
      'helpDataSection': 'データ一覧タブ',
      'helpDataAbnormal': '⚠️ マーク',
      'helpDataAbnormalDesc': '温度差が±10°C以上のデータには警告マークが付きます。',
      'helpDataEdit': 'データを編集する',
      'helpDataEditDesc': '行をタップすると編集シートが開きます。テンキーで値を修正し「保存」を押してください。',
      'helpDataDelete': 'データを削除する',
      'helpDataDeleteDesc': '行を左にスワイプすると削除ボタンが現れます。確認ダイアログで「削除」を押すと削除されます。',
      'helpCategorySection': '区分を削除する',
      'helpCategoryDesc': '① グラフタブの🗑アイコンをタップ\n② 削除したい区分にチェックを入れる\n③「○区分を削除」ボタンをタップ',
      'helpCategoryNote': '注意',
      'helpCategoryNoteDesc': '区分を削除すると、その区分に属するすべての計測データも同時に削除されます。元に戻すことはできません。',
      'helpDeleteAllSection': '全データ削除',
      'helpDeleteAllDesc': '画面右上の🗑アイコンをタップすると、全データを一括削除できます。',
      'helpDeleteAllNote': '注意',
      'helpDeleteAllNoteDesc': 'すべての記録が削除されます。この操作は元に戻せません。',
      'helpExportSection': 'ファイル保存（エクスポート）',
      'helpExportDesc': '画面右上の ↓ アイコンをタップすると形式を選ぶダイアログが表示されます。',
      'helpExportCsv': 'CSV形式',
      'helpExportCsvDesc': 'どの版のExcelでも確実に開けます。4つのファイルに分けて保存されます。',
      'helpExportExcel': 'Excel形式（.xlsx）',
      'helpExportExcelDesc': 'Excel 2007以降で開けます。1ファイルに4シートまとめて保存されます。',
      'helpExportSave': '保存先',
      'helpExportSaveDesc': '端末のダウンロードフォルダに保存されます。',
      // ヘルプ画面
      'helpCalcFormula': '温度補正の計算式',
      'helpCalcFormulaContent': '補正値 = 寸法 × 線膨張係数 × 温度差\n\n・線膨張係数：11.5 × 10⁻⁶ (鉄鋼)\n・温度差：製品温度 － 模範温度',
      'helpCorrectionIdea': '補正の考え方',
      'helpCorrectionContent': '【製品が模範より熱い場合 (+)】\n製品が膨張しているため、マイクロの読み値は本来より大きくなります。真の寸法を得るには補正値を「引き」ます。\n\n【製品が模範より冷たい場合 (-)】\n製品が収縮しているため、読み値は小さくなります。補正値を「足し」ます。',
      'helpFooter': '一体型仕上げ組 温度補正システム v1.0',
      // 早見表
      'tableHeader': '寸法\\差',
      // 共通
      'save': '保存',
      'cancel2': 'キャンセル',
      'warningMark': '⚠ 要確認',
      'editTitle': 'データ編集',
    },

    // ════════════════════════════════════════════════
    'en': {
      'appName': 'Temp Correction System',
      'subtitle': 'Integrated Finishing Team',
      'statsBtn': 'Statistics & Data',
      'langSelect': 'Select Language',
      'navCalcTitle': 'Temperature Correction',
      'navTableTitle': 'Quick Reference Table',
      'navHelpTitle': 'Help & How to Use',
      'fieldSize': 'Product Dimension (mm)',
      'fieldMasterTemp': 'Reference Temp (°C)',
      'fieldWorkTemp': 'Product Temp (°C)',
      'calcBtn': 'Calculate',
      'resultCorrection': 'Correction Value',
      'resultConverted': 'Converted Dimension at Ref. Temp',
      'refTableTitle': '[Reference] Correction Value List',
      'refTableTempDiff': 'Temp Diff',
      'refTableCorrection': 'Correction (mm)',
      'dialogConfirm': 'Confirm',
      'dialogCancel': 'Cancel',
      'dialogExec': 'Calculate',
      'dialogTempWarn': 'Temp diff is {diff}°C.\nOver 10°C — is the input correct?',
      'statsTitle': 'Statistics & Data',
      'tabGraph': 'Graph',
      'tabData': 'Data List',
      'modeMonthly': 'Monthly',
      'modeSize': 'By Size',
      'modeGroup': '50mm Group',
      'howToUse': 'How to Use',
      'export': 'Export',
      'deleteAllBtn': 'Delete All',
      'noData': 'No data available',
      'colCategory': 'Category',
      'colCount': 'Count',
      'colAvg': 'Avg',
      'colMax': 'Max',
      'colMin': 'Min',
      'colStdDev': 'Std Dev',
      'exportTitle': 'Export Format',
      'exportDesc': 'Save to downloads folder.\nSelect a format.',
      'creatingCsv': 'Creating CSV file...',
      'creatingExcel': 'Creating Excel file...',
      'exportSuccess': 'Saved {n} file(s) to downloads folder',
      'exportFail': 'Export failed: check storage permissions',
      'deleteAllTitle': 'Delete All Data',
      'deleteAllMsg': 'All recorded data will be deleted.\nThis cannot be undone.\n\nAre you sure?',
      'deleteTitle': 'Confirm Delete',
      'deleteMsg': 'Delete this record?',
      'deleteBtn': 'Delete',
      'selectCategory': 'Select categories to delete',
      'selectedCount': '{n} selected',
      'deleteCategoryBtn': 'Delete {n} categories',
      'selectFirst': 'Please select a category',
      'helpStatsTitle': 'Statistics & Data — How to Use',
      'helpGraphSection': 'Graph Tab',
      'helpGraphMode': 'Switch View',
      'helpGraphModeDesc': 'Switch between Monthly, By Size, and 50mm Group using the buttons at the top.',
      'helpGraphColor': 'Bar Colors',
      'helpGraphColorDesc': 'Red bar → Product temp higher than reference (+)\nBlue bar → Product temp lower than reference (−)',
      'helpGraphTap': 'Tap for Details',
      'helpGraphTapDesc': 'Tap a bar to see category, average temp diff, and count.',
      'helpGraphTable': 'Summary Table',
      'helpGraphTableDesc': 'Shows count, average, max, and min for each category below the chart.',
      'helpGraphAvg': 'Reading the Average Column',
      'helpGraphAvgDesc': 'Average column is highlighted in yellow.\nRed → Product temp higher\nBlue → Product temp lower',
      'helpGraphSort': 'Sorting',
      'helpGraphSortDesc': 'Tap column headers to sort. ▲▼ icons show current sort order.',
      'helpDataSection': 'Data List Tab',
      'helpDataAbnormal': '⚠️ Mark',
      'helpDataAbnormalDesc': 'Records with temp diff ±10°C or more are marked with a warning.',
      'helpDataEdit': 'Edit a Record',
      'helpDataEditDesc': 'Tap a row to open the edit sheet. Modify values and tap Save.',
      'helpDataDelete': 'Delete a Record',
      'helpDataDeleteDesc': 'Swipe left on a row to reveal the delete button.',
      'helpCategorySection': 'Delete by Category',
      'helpCategoryDesc': '① Tap the 🗑 icon in the Graph tab\n② Check the categories to delete\n③ Tap "Delete X categories"',
      'helpCategoryNote': 'Note',
      'helpCategoryNoteDesc': 'Deleting a category removes all records in that category. This cannot be undone.',
      'helpDeleteAllSection': 'Delete All Data',
      'helpDeleteAllDesc': 'Tap the 🗑 icon at the top right to delete all records at once.',
      'helpDeleteAllNote': 'Note',
      'helpDeleteAllNoteDesc': 'All records will be deleted. This cannot be undone.',
      'helpExportSection': 'Export / Save File',
      'helpExportDesc': 'Tap the ↓ icon at the top right to choose a format.',
      'helpExportCsv': 'CSV Format',
      'helpExportCsvDesc': 'Compatible with any version of Excel. Saved as 4 separate files.',
      'helpExportExcel': 'Excel Format (.xlsx)',
      'helpExportExcelDesc': 'Compatible with Excel 2007+. Saved as 1 file with 4 sheets.',
      'helpExportSave': 'Save Location',
      'helpExportSaveDesc': 'Saved to the device downloads folder.',
      'helpCalcFormula': 'Temperature Correction Formula',
      'helpCalcFormulaContent': 'Correction = Dimension × Linear Expansion Coefficient × Temp Diff\n\n• Linear expansion coefficient: 11.5 × 10⁻⁶ (Steel)\n• Temp diff: Product temp − Reference temp',
      'helpCorrectionIdea': 'Correction Concept',
      'helpCorrectionContent': '[Product hotter than reference (+)]\nProduct is expanded, so the micrometer reading is larger than actual. Subtract the correction value to get the true dimension.\n\n[Product colder than reference (-)]\nProduct is contracted, so the reading is smaller. Add the correction value.',
      'helpFooter': 'Integrated Finishing Team — Temp Correction System v1.0',
      'tableHeader': 'Dim\\Diff',
      'save': 'Save',
      'cancel2': 'Cancel',
      'warningMark': '⚠ Check',
      'editTitle': 'Edit Record',
    },

    // ════════════════════════════════════════════════
    'zh': {
      'appName': '温度补偿系统',
      'subtitle': '综合精加工组',
      'statsBtn': '统计・数据',
      'langSelect': '选择语言',
      'navCalcTitle': '温度补偿计算',
      'navTableTitle': '主要尺寸补偿速查表',
      'navHelpTitle': '帮助・使用方法',
      'fieldSize': '产品尺寸 (mm)',
      'fieldMasterTemp': '基准温度 (°C)',
      'fieldWorkTemp': '产品温度 (°C)',
      'calcBtn': '执行计算',
      'resultCorrection': '本次补偿量',
      'resultConverted': '基准温度下的换算尺寸',
      'refTableTitle': '【参考】温度补偿值一览',
      'refTableTempDiff': '温差',
      'refTableCorrection': '补偿量 (mm)',
      'dialogConfirm': '确认',
      'dialogCancel': '取消',
      'dialogExec': '执行计算',
      'dialogTempWarn': '温差为 {diff}°C。\n超过10°C，输入值是否正确？',
      'statsTitle': '统计・数据',
      'tabGraph': '图表',
      'tabData': '数据列表',
      'modeMonthly': '按月',
      'modeSize': '按尺寸',
      'modeGroup': '50mm组',
      'howToUse': '使用说明',
      'export': '导出',
      'deleteAllBtn': '删除全部',
      'noData': '暂无数据',
      'colCategory': '分类',
      'colCount': '件数',
      'colAvg': '平均',
      'colMax': '最大',
      'colMin': '最小',
      'colStdDev': '标准差',
      'exportTitle': '导出格式',
      'exportDesc': '保存到下载文件夹。\n请选择格式。',
      'creatingCsv': '正在创建CSV文件...',
      'creatingExcel': '正在创建Excel文件...',
      'exportSuccess': '已保存{n}个文件到下载文件夹',
      'exportFail': '导出失败：请检查存储权限',
      'deleteAllTitle': '删除全部数据',
      'deleteAllMsg': '将删除所有记录数据。\n此操作无法撤销。\n\n确定吗？',
      'deleteTitle': '确认删除',
      'deleteMsg': '删除此数据？',
      'deleteBtn': '删除',
      'selectCategory': '选择要删除的分类',
      'selectedCount': '已选{n}项',
      'deleteCategoryBtn': '删除{n}个分类',
      'selectFirst': '请先选择分类',
      'helpStatsTitle': '统计・数据　使用说明',
      'helpGraphSection': '图表标签页',
      'helpGraphMode': '切换显示',
      'helpGraphModeDesc': '点击顶部「按月」「按尺寸」「50mm组」按钮切换统计方式。',
      'helpGraphColor': '柱状图颜色',
      'helpGraphColorDesc': '红色柱 → 产品温度高于基准（+）\n蓝色柱 → 产品温度低于基准（−）',
      'helpGraphTap': '点击查看详情',
      'helpGraphTapDesc': '点击柱子可查看分类名、平均温差和件数。',
      'helpGraphTable': '汇总表',
      'helpGraphTableDesc': '图表下方显示各分类的件数、平均、最大、最小值。',
      'helpGraphAvg': '平均列说明',
      'helpGraphAvgDesc': '平均列以黄色背景加粗显示。\n红字 → 产品温度高于基准\n蓝字 → 产品温度低于基准',
      'helpGraphSort': '排序',
      'helpGraphSortDesc': '点击表头可按该列排序，▲▼图标显示当前排序方向。',
      'helpDataSection': '数据列表标签页',
      'helpDataAbnormal': '⚠️ 标记',
      'helpDataAbnormalDesc': '温差±10°C以上的数据会显示警告标记。',
      'helpDataEdit': '编辑数据',
      'helpDataEditDesc': '点击行打开编辑面板，修改数值后点击「保存」。',
      'helpDataDelete': '删除数据',
      'helpDataDeleteDesc': '向左滑动行即可显示删除按钮。',
      'helpCategorySection': '按分类删除',
      'helpCategoryDesc': '① 点击图表标签页中的🗑图标\n② 勾选要删除的分类\n③ 点击「删除○个分类」按钮',
      'helpCategoryNote': '注意',
      'helpCategoryNoteDesc': '删除分类将同时删除该分类下的所有数据，无法恢复。',
      'helpDeleteAllSection': '删除全部数据',
      'helpDeleteAllDesc': '点击右上角🗑图标可一键删除全部数据。',
      'helpDeleteAllNote': '注意',
      'helpDeleteAllNoteDesc': '所有记录将被删除，此操作无法撤销。',
      'helpExportSection': '文件导出',
      'helpExportDesc': '点击右上角↓图标选择导出格式。',
      'helpExportCsv': 'CSV格式',
      'helpExportCsvDesc': '兼容所有版本的Excel，分4个文件保存。',
      'helpExportExcel': 'Excel格式（.xlsx）',
      'helpExportExcelDesc': '兼容Excel 2007及以上，1个文件包含4个工作表。',
      'helpExportSave': '保存位置',
      'helpExportSaveDesc': '保存到设备的下载文件夹。',
      'helpCalcFormula': '温度补偿计算公式',
      'helpCalcFormulaContent': '补偿值 = 尺寸 × 线膨胀系数 × 温差\n\n• 线膨胀系数：11.5 × 10⁻⁶（钢铁）\n• 温差：产品温度 － 基准温度',
      'helpCorrectionIdea': '补偿原理',
      'helpCorrectionContent': '【产品温度高于基准 (+)】\n产品膨胀，千分尺读数偏大。需减去补偿值才能得到真实尺寸。\n\n【产品温度低于基准 (-)】\n产品收缩，读数偏小。需加上补偿值。',
      'helpFooter': '综合精加工组 温度补偿系统 v1.0',
      'tableHeader': '尺寸\\差',
      'save': '保存',
      'cancel2': '取消',
      'warningMark': '⚠ 需确认',
      'editTitle': '编辑数据',
    },

    // ════════════════════════════════════════════════
    'ko': {
      'appName': '온도 보정 시스템',
      'subtitle': '통합 마무리 공정팀',
      'statsBtn': '통계・데이터',
      'langSelect': '언어 선택',
      'navCalcTitle': '온도 보정 계산',
      'navTableTitle': '주요 치수 보정 속견표',
      'navHelpTitle': '도움말・사용 방법',
      'fieldSize': '제품 치수 (mm)',
      'fieldMasterTemp': '기준 온도 (°C)',
      'fieldWorkTemp': '제품 온도 (°C)',
      'calcBtn': '계산 실행',
      'resultCorrection': '이번 보정량',
      'resultConverted': '기준 온도 환산 치수',
      'refTableTitle': '【참고】온도 보정값 목록',
      'refTableTempDiff': '온도차',
      'refTableCorrection': '보정량 (mm)',
      'dialogConfirm': '확인',
      'dialogCancel': '취소',
      'dialogExec': '계산 실행',
      'dialogTempWarn': '온도차가 {diff}°C 입니다.\n10°C 이상인데 입력값이 맞나요?',
      'statsTitle': '통계・데이터',
      'tabGraph': '그래프',
      'tabData': '데이터 목록',
      'modeMonthly': '월별',
      'modeSize': '치수별',
      'modeGroup': '50mm 그룹',
      'howToUse': '사용 방법',
      'export': '내보내기',
      'deleteAllBtn': '전체 삭제',
      'noData': '데이터가 없습니다',
      'colCategory': '구분',
      'colCount': '건수',
      'colAvg': '평균',
      'colMax': '최대',
      'colMin': '최소',
      'colStdDev': '표준편차',
      'exportTitle': '내보내기 형식',
      'exportDesc': '다운로드 폴더에 저장합니다.\n형식을 선택하세요.',
      'creatingCsv': 'CSV 파일 생성 중...',
      'creatingExcel': 'Excel 파일 생성 중...',
      'exportSuccess': '{n}개 파일을 다운로드 폴더에 저장했습니다',
      'exportFail': '내보내기 실패: 저장소 권한을 확인하세요',
      'deleteAllTitle': '전체 데이터 삭제',
      'deleteAllMsg': '모든 기록 데이터를 삭제합니다.\n이 작업은 되돌릴 수 없습니다.\n\n계속하시겠습니까?',
      'deleteTitle': '삭제 확인',
      'deleteMsg': '이 데이터를 삭제하시겠습니까?',
      'deleteBtn': '삭제',
      'selectCategory': '삭제할 구분 선택',
      'selectedCount': '{n}건 선택됨',
      'deleteCategoryBtn': '{n}개 구분 삭제',
      'selectFirst': '구분을 선택해 주세요',
      'helpStatsTitle': '통계・데이터　사용 방법',
      'helpGraphSection': '그래프 탭',
      'helpGraphMode': '표시 전환',
      'helpGraphModeDesc': '상단의 「월별」「치수별」「50mm 그룹」 버튼으로 집계 방식을 전환합니다.',
      'helpGraphColor': '막대 그래프 색상',
      'helpGraphColorDesc': '빨간 막대 → 제품 온도가 기준보다 높음 (+)\n파란 막대 → 제품 온도가 기준보다 낮음 (−)',
      'helpGraphTap': '탭으로 상세 보기',
      'helpGraphTapDesc': '막대를 탭하면 구분명, 평균 온도차, 건수가 표시됩니다.',
      'helpGraphTable': '집계 테이블',
      'helpGraphTableDesc': '그래프 하단에 각 구분의 건수・평균・최대・최소가 표시됩니다.',
      'helpGraphAvg': '평균 열 보는 방법',
      'helpGraphAvgDesc': '평균 열은 노란 배경・굵은 글씨로 강조됩니다.\n빨간 글씨 → 제품 온도가 기준보다 높음\n파란 글씨 → 제품 온도가 기준보다 낮음',
      'helpGraphSort': '정렬',
      'helpGraphSortDesc': '열 헤더를 탭하면 해당 열로 정렬됩니다. ▲▼ 아이콘으로 현재 정렬 방향을 확인합니다.',
      'helpDataSection': '데이터 목록 탭',
      'helpDataAbnormal': '⚠️ 마크',
      'helpDataAbnormalDesc': '온도차 ±10°C 이상의 데이터에 경고 마크가 표시됩니다.',
      'helpDataEdit': '데이터 편집',
      'helpDataEditDesc': '행을 탭하면 편집 시트가 열립니다. 수정 후 「저장」을 누르세요.',
      'helpDataDelete': '데이터 삭제',
      'helpDataDeleteDesc': '행을 왼쪽으로 스와이프하면 삭제 버튼이 나타납니다.',
      'helpCategorySection': '구분 삭제',
      'helpCategoryDesc': '① 그래프 탭의 🗑 아이콘 탭\n② 삭제할 구분에 체크\n③ 「○구분 삭제」 버튼 탭',
      'helpCategoryNote': '주의',
      'helpCategoryNoteDesc': '구분을 삭제하면 해당 구분의 모든 데이터도 삭제됩니다. 되돌릴 수 없습니다.',
      'helpDeleteAllSection': '전체 데이터 삭제',
      'helpDeleteAllDesc': '오른쪽 상단 🗑 아이콘을 탭하면 전체 데이터를 일괄 삭제합니다.',
      'helpDeleteAllNote': '주의',
      'helpDeleteAllNoteDesc': '모든 기록이 삭제됩니다. 되돌릴 수 없습니다.',
      'helpExportSection': '파일 저장 (내보내기)',
      'helpExportDesc': '오른쪽 상단 ↓ 아이콘을 탭하면 형식 선택 다이얼로그가 표시됩니다.',
      'helpExportCsv': 'CSV 형식',
      'helpExportCsvDesc': '모든 버전의 Excel에서 열 수 있습니다. 4개 파일로 저장됩니다.',
      'helpExportExcel': 'Excel 형식 (.xlsx)',
      'helpExportExcelDesc': 'Excel 2007 이상에서 열 수 있습니다. 4개 시트가 포함된 1개 파일로 저장됩니다.',
      'helpExportSave': '저장 위치',
      'helpExportSaveDesc': '기기의 다운로드 폴더에 저장됩니다.',
      'helpCalcFormula': '온도 보정 계산식',
      'helpCalcFormulaContent': '보정값 = 치수 × 선팽창계수 × 온도차\n\n• 선팽창계수: 11.5 × 10⁻⁶ (철강)\n• 온도차: 제품 온도 − 기준 온도',
      'helpCorrectionIdea': '보정 개념',
      'helpCorrectionContent': '【제품이 기준보다 뜨거운 경우 (+)】\n제품이 팽창하여 마이크로미터 값이 실제보다 크게 나타납니다. 실제 치수를 얻으려면 보정값을 뺍니다.\n\n【제품이 기준보다 차가운 경우 (-)】\n제품이 수축하여 값이 작게 나타납니다. 보정값을 더합니다.',
      'helpFooter': '통합 마무리 공정팀 온도 보정 시스템 v1.0',
      'tableHeader': '치수\\차',
      'save': '저장',
      'cancel2': '취소',
      'warningMark': '⚠ 확인 필요',
      'editTitle': '데이터 편집',
    },

    // ════════════════════════════════════════════════
    'hi': {
      'appName': 'तापमान सुधार प्रणाली',
      'subtitle': 'एकीकृत फिनिशिंग टीम',
      'statsBtn': 'आँकड़े・डेटा',
      'langSelect': 'भाषा चुनें',
      'navCalcTitle': 'तापमान सुधार गणना',
      'navTableTitle': 'त्वरित संदर्भ तालिका',
      'navHelpTitle': 'सहायता・उपयोग विधि',
      'fieldSize': 'उत्पाद का आयाम (mm)',
      'fieldMasterTemp': 'संदर्भ तापमान (°C)',
      'fieldWorkTemp': 'उत्पाद तापमान (°C)',
      'calcBtn': 'गणना करें',
      'resultCorrection': 'सुधार मान',
      'resultConverted': 'संदर्भ तापमान पर परिवर्तित आयाम',
      'refTableTitle': '【संदर्भ】तापमान सुधार मान सूची',
      'refTableTempDiff': 'तापमान अंतर',
      'refTableCorrection': 'सुधार (mm)',
      'dialogConfirm': 'पुष्टि करें',
      'dialogCancel': 'रद्द करें',
      'dialogExec': 'गणना करें',
      'dialogTempWarn': 'तापमान अंतर {diff}°C है।\n10°C से अधिक — क्या इनपुट सही है?',
      'statsTitle': 'आँकड़े・डेटा',
      'tabGraph': 'ग्राफ',
      'tabData': 'डेटा सूची',
      'modeMonthly': 'मासिक',
      'modeSize': 'आयाम अनुसार',
      'modeGroup': '50mm समूह',
      'howToUse': 'उपयोग विधि',
      'export': 'निर्यात',
      'deleteAllBtn': 'सब हटाएं',
      'noData': 'कोई डेटा नहीं',
      'colCategory': 'श्रेणी',
      'colCount': 'संख्या',
      'colAvg': 'औसत',
      'colMax': 'अधिकतम',
      'colMin': 'न्यूनतम',
      'colStdDev': 'मानक विचलन',
      'exportTitle': 'निर्यात प्रारूप',
      'exportDesc': 'डाउनलोड फ़ोल्डर में सहेजें।\nप्रारूप चुनें।',
      'creatingCsv': 'CSV फ़ाइल बना रहे हैं...',
      'creatingExcel': 'Excel फ़ाइल बना रहे हैं...',
      'exportSuccess': '{n} फ़ाइलें डाउनलोड फ़ोल्डर में सहेजी गईं',
      'exportFail': 'निर्यात विफल: स्टोरेज अनुमति जाँचें',
      'deleteAllTitle': 'सभी डेटा हटाएं',
      'deleteAllMsg': 'सभी रिकॉर्ड हटा दिए जाएंगे।\nयह क्रिया पूर्ववत नहीं हो सकती।\n\nक्या आप सुनिश्चित हैं?',
      'deleteTitle': 'हटाने की पुष्टि',
      'deleteMsg': 'यह डेटा हटाएं?',
      'deleteBtn': 'हटाएं',
      'selectCategory': 'हटाने के लिए श्रेणी चुनें',
      'selectedCount': '{n} चुने गए',
      'deleteCategoryBtn': '{n} श्रेणियाँ हटाएं',
      'selectFirst': 'कृपया श्रेणी चुनें',
      'helpStatsTitle': 'आँकड़े・डेटा　उपयोग विधि',
      'helpGraphSection': 'ग्राफ टैब',
      'helpGraphMode': 'दृश्य बदलें',
      'helpGraphModeDesc': 'शीर्ष पर मासिक/आयाम/50mm बटन से संकलन बदलें।',
      'helpGraphColor': 'बार रंग',
      'helpGraphColorDesc': 'लाल बार → उत्पाद तापमान संदर्भ से अधिक (+)\nनीला बार → उत्पाद तापमान संदर्भ से कम (−)',
      'helpGraphTap': 'विवरण के लिए टैप करें',
      'helpGraphTapDesc': 'बार टैप करने पर श्रेणी, औसत तापमान अंतर और संख्या दिखेगी।',
      'helpGraphTable': 'सारांश तालिका',
      'helpGraphTableDesc': 'ग्राफ के नीचे प्रत्येक श्रेणी की संख्या, औसत, अधिकतम, न्यूनतम दिखाई देती है।',
      'helpGraphAvg': 'औसत कॉलम',
      'helpGraphAvgDesc': 'औसत कॉलम पीली पृष्ठभूमि से हाइलाइट।\nलाल → उत्पाद अधिक गर्म\nनीला → उत्पाद कम गर्म',
      'helpGraphSort': 'क्रमबद्ध करें',
      'helpGraphSortDesc': 'कॉलम हेडर टैप करके क्रमबद्ध करें। ▲▼ आइकन क्रम दिखाते हैं।',
      'helpDataSection': 'डेटा सूची टैब',
      'helpDataAbnormal': '⚠️ चिह्न',
      'helpDataAbnormalDesc': 'तापमान अंतर ±10°C या अधिक होने पर चेतावनी चिह्न लगता है।',
      'helpDataEdit': 'डेटा संपादित करें',
      'helpDataEditDesc': 'पंक्ति टैप करके संपादन खोलें। मान बदलें और सहेजें टैप करें।',
      'helpDataDelete': 'डेटा हटाएं',
      'helpDataDeleteDesc': 'पंक्ति को बाईं ओर स्वाइप करें।',
      'helpCategorySection': 'श्रेणी हटाएं',
      'helpCategoryDesc': '① ग्राफ टैब में 🗑 टैप करें\n② हटाने की श्रेणियाँ चुनें\n③ श्रेणियाँ हटाएं बटन टैप करें',
      'helpCategoryNote': 'नोट',
      'helpCategoryNoteDesc': 'श्रेणी हटाने से उसमें सभी डेटा भी हट जाएगा।',
      'helpDeleteAllSection': 'सभी डेटा हटाएं',
      'helpDeleteAllDesc': 'ऊपर दाईं ओर 🗑 टैप करके सब हटाएं।',
      'helpDeleteAllNote': 'नोट',
      'helpDeleteAllNoteDesc': 'सभी रिकॉर्ड हट जाएंगे। यह पूर्ववत नहीं हो सकता।',
      'helpExportSection': 'फ़ाइल निर्यात',
      'helpExportDesc': 'ऊपर दाईं ओर ↓ टैप करके प्रारूप चुनें।',
      'helpExportCsv': 'CSV प्रारूप',
      'helpExportCsvDesc': 'Excel के सभी संस्करणों में खुलता है। 4 फ़ाइलों में सहेजा जाता है।',
      'helpExportExcel': 'Excel प्रारूप (.xlsx)',
      'helpExportExcelDesc': 'Excel 2007+ में खुलता है। 4 शीट वाली 1 फ़ाइल।',
      'helpExportSave': 'सहेजने का स्थान',
      'helpExportSaveDesc': 'डिवाइस के डाउनलोड फ़ोल्डर में सहेजा जाता है।',
      'helpCalcFormula': 'तापमान सुधार सूत्र',
      'helpCalcFormulaContent': 'सुधार = आयाम × रैखिक विस्तार गुणांक × तापमान अंतर\n\n• रैखिक विस्तार गुणांक: 11.5 × 10⁻⁶ (इस्पात)\n• तापमान अंतर: उत्पाद तापमान − संदर्भ तापमान',
      'helpCorrectionIdea': 'सुधार की अवधारणा',
      'helpCorrectionContent': '【उत्पाद संदर्भ से गर्म (+)】\nउत्पाद फैला हुआ है, माइक्रोमीटर रीडिंग वास्तविक से बड़ी है। सही आयाम के लिए सुधार मान घटाएं।\n\n【उत्पाद संदर्भ से ठंडा (-)】\nउत्पाद सिकुड़ा हुआ है, रीडिंग छोटी है। सुधार मान जोड़ें।',
      'helpFooter': 'एकीकृत फिनिशिंग टीम — तापमान सुधार प्रणाली v1.0',
      'tableHeader': 'आयाम\\अंतर',
      'save': 'सहेजें',
      'cancel2': 'रद्द',
      'warningMark': '⚠ जाँचें',
      'editTitle': 'डेटा संपादित करें',
    },

    // ════════════════════════════════════════════════
    'vi': {
      'appName': 'Hệ Thống Hiệu Chỉnh Nhiệt Độ',
      'subtitle': 'Nhóm Gia Công Hoàn Thiện',
      'statsBtn': 'Thống Kê・Dữ Liệu',
      'langSelect': 'Chọn Ngôn Ngữ',
      'navCalcTitle': 'Tính Hiệu Chỉnh Nhiệt Độ',
      'navTableTitle': 'Bảng Tra Cứu Nhanh',
      'navHelpTitle': 'Trợ Giúp・Hướng Dẫn',
      'fieldSize': 'Kích Thước Sản Phẩm (mm)',
      'fieldMasterTemp': 'Nhiệt Độ Chuẩn (°C)',
      'fieldWorkTemp': 'Nhiệt Độ Sản Phẩm (°C)',
      'calcBtn': 'Tính Toán',
      'resultCorrection': 'Giá Trị Hiệu Chỉnh',
      'resultConverted': 'Kích Thước Quy Đổi Tại Nhiệt Độ Chuẩn',
      'refTableTitle': '【Tham Khảo】Bảng Giá Trị Hiệu Chỉnh',
      'refTableTempDiff': 'Hiệu Nhiệt Độ',
      'refTableCorrection': 'Hiệu Chỉnh (mm)',
      'dialogConfirm': 'Xác Nhận',
      'dialogCancel': 'Hủy',
      'dialogExec': 'Tính Toán',
      'dialogTempWarn': 'Hiệu nhiệt độ là {diff}°C.\nVượt 10°C — giá trị nhập có đúng không?',
      'statsTitle': 'Thống Kê・Dữ Liệu',
      'tabGraph': 'Biểu Đồ',
      'tabData': 'Danh Sách Dữ Liệu',
      'modeMonthly': 'Theo Tháng',
      'modeSize': 'Theo Kích Thước',
      'modeGroup': 'Nhóm 50mm',
      'howToUse': 'Hướng Dẫn',
      'export': 'Xuất File',
      'deleteAllBtn': 'Xóa Tất Cả',
      'noData': 'Không có dữ liệu',
      'colCategory': 'Danh Mục',
      'colCount': 'Số Lượng',
      'colAvg': 'TB',
      'colMax': 'Max',
      'colMin': 'Min',
      'colStdDev': 'Độ Lệch Chuẩn',
      'exportTitle': 'Định Dạng Xuất',
      'exportDesc': 'Lưu vào thư mục tải về.\nChọn định dạng.',
      'creatingCsv': 'Đang tạo file CSV...',
      'creatingExcel': 'Đang tạo file Excel...',
      'exportSuccess': 'Đã lưu {n} file vào thư mục tải về',
      'exportFail': 'Xuất thất bại: kiểm tra quyền lưu trữ',
      'deleteAllTitle': 'Xóa Tất Cả Dữ Liệu',
      'deleteAllMsg': 'Tất cả dữ liệu sẽ bị xóa.\nThao tác này không thể hoàn tác.\n\nBạn có chắc không?',
      'deleteTitle': 'Xác Nhận Xóa',
      'deleteMsg': 'Xóa dữ liệu này?',
      'deleteBtn': 'Xóa',
      'selectCategory': 'Chọn danh mục để xóa',
      'selectedCount': 'Đã chọn {n}',
      'deleteCategoryBtn': 'Xóa {n} danh mục',
      'selectFirst': 'Vui lòng chọn danh mục',
      'helpStatsTitle': 'Thống Kê・Dữ Liệu　Hướng Dẫn',
      'helpGraphSection': 'Tab Biểu Đồ',
      'helpGraphMode': 'Chuyển Chế Độ Xem',
      'helpGraphModeDesc': 'Chuyển đổi giữa Theo Tháng, Theo Kích Thước, Nhóm 50mm bằng các nút phía trên.',
      'helpGraphColor': 'Màu Cột',
      'helpGraphColorDesc': 'Cột đỏ → Nhiệt độ sản phẩm cao hơn chuẩn (+)\nCột xanh → Nhiệt độ sản phẩm thấp hơn chuẩn (−)',
      'helpGraphTap': 'Nhấn để Xem Chi Tiết',
      'helpGraphTapDesc': 'Nhấn vào cột để xem tên danh mục, hiệu nhiệt độ trung bình và số lượng.',
      'helpGraphTable': 'Bảng Tổng Hợp',
      'helpGraphTableDesc': 'Hiển thị số lượng, trung bình, max, min cho mỗi danh mục bên dưới biểu đồ.',
      'helpGraphAvg': 'Cột Trung Bình',
      'helpGraphAvgDesc': 'Cột TB được làm nổi bật bằng nền vàng.\nChữ đỏ → Nhiệt độ cao hơn\nChữ xanh → Nhiệt độ thấp hơn',
      'helpGraphSort': 'Sắp Xếp',
      'helpGraphSortDesc': 'Nhấn tiêu đề cột để sắp xếp. Biểu tượng ▲▼ cho biết thứ tự hiện tại.',
      'helpDataSection': 'Tab Danh Sách Dữ Liệu',
      'helpDataAbnormal': 'Dấu ⚠️',
      'helpDataAbnormalDesc': 'Dữ liệu có hiệu nhiệt độ ±10°C trở lên sẽ có dấu cảnh báo.',
      'helpDataEdit': 'Chỉnh Sửa Dữ Liệu',
      'helpDataEditDesc': 'Nhấn vào hàng để mở bảng chỉnh sửa. Sửa giá trị rồi nhấn Lưu.',
      'helpDataDelete': 'Xóa Dữ Liệu',
      'helpDataDeleteDesc': 'Vuốt trái hàng để hiển thị nút xóa.',
      'helpCategorySection': 'Xóa Theo Danh Mục',
      'helpCategoryDesc': '① Nhấn biểu tượng 🗑 trong tab Biểu Đồ\n② Chọn danh mục cần xóa\n③ Nhấn nút Xóa danh mục',
      'helpCategoryNote': 'Lưu Ý',
      'helpCategoryNoteDesc': 'Xóa danh mục sẽ xóa toàn bộ dữ liệu trong đó. Không thể hoàn tác.',
      'helpDeleteAllSection': 'Xóa Tất Cả',
      'helpDeleteAllDesc': 'Nhấn biểu tượng 🗑 phía trên bên phải để xóa tất cả dữ liệu.',
      'helpDeleteAllNote': 'Lưu Ý',
      'helpDeleteAllNoteDesc': 'Tất cả bản ghi sẽ bị xóa. Không thể hoàn tác.',
      'helpExportSection': 'Xuất File',
      'helpExportDesc': 'Nhấn biểu tượng ↓ phía trên bên phải để chọn định dạng.',
      'helpExportCsv': 'Định Dạng CSV',
      'helpExportCsvDesc': 'Tương thích mọi phiên bản Excel. Lưu thành 4 file riêng biệt.',
      'helpExportExcel': 'Định Dạng Excel (.xlsx)',
      'helpExportExcelDesc': 'Tương thích Excel 2007+. Lưu 1 file với 4 sheet.',
      'helpExportSave': 'Vị Trí Lưu',
      'helpExportSaveDesc': 'Lưu vào thư mục tải về của thiết bị.',
      'helpCalcFormula': 'Công Thức Hiệu Chỉnh Nhiệt Độ',
      'helpCalcFormulaContent': 'Hiệu chỉnh = Kích thước × Hệ số giãn nở tuyến tính × Hiệu nhiệt độ\n\n• Hệ số giãn nở: 11.5 × 10⁻⁶ (Thép)\n• Hiệu nhiệt độ: Nhiệt độ sản phẩm − Nhiệt độ chuẩn',
      'helpCorrectionIdea': 'Khái Niệm Hiệu Chỉnh',
      'helpCorrectionContent': '【Sản phẩm nóng hơn chuẩn (+)】\nSản phẩm giãn nở, số đo micromet lớn hơn thực tế. Trừ giá trị hiệu chỉnh để có kích thước thực.\n\n【Sản phẩm lạnh hơn chuẩn (-)】\nSản phẩm co lại, số đo nhỏ hơn. Cộng giá trị hiệu chỉnh.',
      'helpFooter': 'Nhóm Gia Công Hoàn Thiện — Hệ Thống Hiệu Chỉnh Nhiệt Độ v1.0',
      'tableHeader': 'KT\\Chênh',
      'save': 'Lưu',
      'cancel2': 'Hủy',
      'warningMark': '⚠ Kiểm Tra',
      'editTitle': 'Chỉnh Sửa Dữ Liệu',
    },

    // ════════════════════════════════════════════════
    'fil': {
      'appName': 'Temperatura Correction System',
      'subtitle': 'Integrated Finishing Team',
      'statsBtn': 'Estadistika・Data',
      'langSelect': 'Pumili ng Wika',
      'navCalcTitle': 'Temperatura Correction Calculation',
      'navTableTitle': 'Mabilis na Sanggunian',
      'navHelpTitle': 'Tulong・Paano Gamitin',
      'fieldSize': 'Sukat ng Produkto (mm)',
      'fieldMasterTemp': 'Sangguniang Temperatura (°C)',
      'fieldWorkTemp': 'Temperatura ng Produkto (°C)',
      'calcBtn': 'Kalkulahin',
      'resultCorrection': 'Halaga ng Pagwawasto',
      'resultConverted': 'Na-convert na Sukat sa Ref. Temperatura',
      'refTableTitle': '【Sanggunian】Listahan ng Correction Value',
      'refTableTempDiff': 'Pagkakaiba ng Temp',
      'refTableCorrection': 'Pagwawasto (mm)',
      'dialogConfirm': 'Kumpirmahin',
      'dialogCancel': 'Kanselahin',
      'dialogExec': 'Kalkulahin',
      'dialogTempWarn': 'Ang pagkakaiba ng temp ay {diff}°C.\nHigit sa 10°C — tama ba ang input?',
      'statsTitle': 'Estadistika・Data',
      'tabGraph': 'Grapiko',
      'tabData': 'Listahan ng Data',
      'modeMonthly': 'Buwanan',
      'modeSize': 'Ayon sa Sukat',
      'modeGroup': 'Grupo ng 50mm',
      'howToUse': 'Paano Gamitin',
      'export': 'I-export',
      'deleteAllBtn': 'Burahin Lahat',
      'noData': 'Walang data',
      'colCategory': 'Kategorya',
      'colCount': 'Bilang',
      'colAvg': 'Karaniwan',
      'colMax': 'Pinakamataas',
      'colMin': 'Pinakamababa',
      'colStdDev': 'Std Dev',
      'exportTitle': 'Format ng Export',
      'exportDesc': 'I-save sa download folder.\nPumili ng format.',
      'creatingCsv': 'Gumagawa ng CSV file...',
      'creatingExcel': 'Gumagawa ng Excel file...',
      'exportSuccess': 'Na-save ang {n} file sa download folder',
      'exportFail': 'Nabigo ang export: tingnan ang storage permission',
      'deleteAllTitle': 'Burahin Lahat ng Data',
      'deleteAllMsg': 'Lahat ng naitalang data ay mabubura.\nHindi ito maaaring ibalik.\n\nSigurado ka ba?',
      'deleteTitle': 'Kumpirmahin ang Pagbura',
      'deleteMsg': 'Burahin ang data na ito?',
      'deleteBtn': 'Burahin',
      'selectCategory': 'Pumili ng kategorya para burahin',
      'selectedCount': '{n} napili',
      'deleteCategoryBtn': 'Burahin ang {n} kategorya',
      'selectFirst': 'Mangyaring pumili ng kategorya',
      'helpStatsTitle': 'Estadistika・Data　Paano Gamitin',
      'helpGraphSection': 'Tab ng Grapiko',
      'helpGraphMode': 'Palitan ang View',
      'helpGraphModeDesc': 'Palitan sa pagitan ng Buwanan, Ayon sa Sukat, at Grupo ng 50mm gamit ang mga button sa itaas.',
      'helpGraphColor': 'Kulay ng Bar',
      'helpGraphColorDesc': 'Pulang bar → Temperatura ng produkto mas mataas (+)\nAsul na bar → Temperatura ng produkto mas mababa (−)',
      'helpGraphTap': 'I-tap para sa Detalye',
      'helpGraphTapDesc': 'I-tap ang bar para makita ang kategorya, average temp diff, at bilang.',
      'helpGraphTable': 'Talahanayan ng Buod',
      'helpGraphTableDesc': 'Ipinapakita ang bilang, average, max, min para sa bawat kategorya sa ibaba ng grapiko.',
      'helpGraphAvg': 'Paliwanag sa Kolum ng Average',
      'helpGraphAvgDesc': 'Ang kolum ng average ay naka-highlight sa dilaw.\nPula → Temperatura mas mataas\nAsul → Temperatura mas mababa',
      'helpGraphSort': 'Pag-aayos',
      'helpGraphSortDesc': 'I-tap ang header ng kolum para ayusin. Ang mga icon na ▲▼ ay nagpapakita ng kasalukuyang order.',
      'helpDataSection': 'Tab ng Listahan ng Data',
      'helpDataAbnormal': 'Tanda ng ⚠️',
      'helpDataAbnormalDesc': 'Ang data na may temp diff na ±10°C o higit ay may babala.',
      'helpDataEdit': 'I-edit ang Data',
      'helpDataEditDesc': 'I-tap ang row para buksan ang edit sheet. Baguhin ang mga value at i-tap ang I-save.',
      'helpDataDelete': 'Burahin ang Data',
      'helpDataDeleteDesc': 'I-swipe pakaliwa ang row para makita ang button ng pagbura.',
      'helpCategorySection': 'Burahin ayon sa Kategorya',
      'helpCategoryDesc': '① I-tap ang icon na 🗑 sa tab ng Grapiko\n② Piliin ang mga kategoryang buburahin\n③ I-tap ang "Burahin ang X kategorya"',
      'helpCategoryNote': 'Paalala',
      'helpCategoryNoteDesc': 'Ang pagbura ng kategorya ay nagtatanggal din ng lahat ng data nito. Hindi ito maaaring ibalik.',
      'helpDeleteAllSection': 'Burahin Lahat ng Data',
      'helpDeleteAllDesc': 'I-tap ang icon na 🗑 sa kanang itaas para burahin ang lahat ng data.',
      'helpDeleteAllNote': 'Paalala',
      'helpDeleteAllNoteDesc': 'Lahat ng record ay mabubura. Hindi ito maaaring ibalik.',
      'helpExportSection': 'I-export ang File',
      'helpExportDesc': 'I-tap ang icon na ↓ sa kanang itaas para pumili ng format.',
      'helpExportCsv': 'Format na CSV',
      'helpExportCsvDesc': 'Tugma sa lahat ng bersyon ng Excel. Sine-save bilang 4 na file.',
      'helpExportExcel': 'Format na Excel (.xlsx)',
      'helpExportExcelDesc': 'Tugma sa Excel 2007+. 1 file na may 4 na sheet.',
      'helpExportSave': 'Lokasyon ng Pag-save',
      'helpExportSaveDesc': 'Sine-save sa download folder ng device.',
      'helpCalcFormula': 'Formula ng Pagwawasto ng Temperatura',
      'helpCalcFormulaContent': 'Pagwawasto = Sukat × Linear Expansion Coefficient × Pagkakaiba ng Temp\n\n• Linear expansion coefficient: 11.5 × 10⁻⁶ (Bakal)\n• Pagkakaiba ng temp: Temp ng produkto − Sangguniang temp',
      'helpCorrectionIdea': 'Konsepto ng Pagwawasto',
      'helpCorrectionContent': '【Produkto mas mainit kaysa sanggunian (+)】\nNag-expand ang produkto, kaya mas malaki ang basahin ng micrometer. Ibawas ang correction value para makuha ang tunay na sukat.\n\n【Produkto mas malamig kaysa sanggunian (-)】\nNag-shrink ang produkto, mas maliit ang basahin. Dagdagan ng correction value.',
      'helpFooter': 'Integrated Finishing Team — Temperatura Correction System v1.0',
      'tableHeader': 'Sukat\\Diff',
      'save': 'I-save',
      'cancel2': 'Kanselahin',
      'warningMark': '⚠ Suriin',
      'editTitle': 'I-edit ang Data',
    },
  };
}
